
[project]
name = "demo-chalk"
version = "0.1.0"
description = "Chalk pilot for Demo Chalk"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "chalkdf>=3.43.14",
  "chalkpy[postgresql,runtime]",
 "chalkcompute"
]

[tool.uv]
dev-dependencies = [
  "pytest>=7.0",
  "pytest-cov>=4.0",
  "black>=23.0",
  "isort>=5.0",
  "flake8>=6.0",
  "ipython>=8.37.0",
  "jupyter>=1.1.1",
  "ipykernel>=6.29.5",
  "torch",
  "onnxruntime",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.pyright]
ignore = ["."]

[tool.mypy]
ignore_errors = true

[tool.ty.rules]
all = "ignore"
